export const shoes=[
    {
        pic:"images/shoe1.jfif",
        brand:"puma",
        model:"idp",
        type:"sneakers",
        colors:['blue','white','black','red'],
        cost:1870
    },
    {
        pic:"images/shoe2.jfif",
        brand:"adidas",
        model:"leather",
        type:"casual",
        colors:['maroon','black'],
        cost:5301
    },
    {
        pic:"images/shoe3.jpeg",
        brand:"puma",
        model:"pro",
        type:"formals",
        colors:['black','red'],
        cost:2300
    },
    {
        pic:"images/shoe4.jfif",
        brand:"nike",
        model:"dash",
        type:"casual",
        colors:['blue','white','black','red','grey','maroon','green'],
        cost:2310
    }
]


export const beanbags=[
    {
        pic:"images/bag1.jfif",
        brand:"Syntel",
        size:[3,2,5],
        cost:4500
    },
    {
        pic:"images/bag2.jfif",
        brand:"FlipPro",
        size:[3,2],
        cost:3500
    },
    {
        pic:"images/bag3.jfif",
        brand:"BagMass",
        size:[4,5],
        cost:6500
    }
]